name: Weekly Code Review

on:
  schedule:
    - cron: '0 15 * * 6' # 每周六23:00北京时间(UTC+8)
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run on (e.g. llm, master)'
        required: false
        default: ${{ github.ref_name }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install deepseek-api python-dotenv

      - name: Run weekly review
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          python .github/scripts/weekly_code_review.py
